theme: jekyll-theme-minimal

title: Trello for macOS (unofficial)
description: Use Trello as a native macOS application.

google_analytics: UA-41066869-1
show_downloads: false

download: https://github.com/nathanbirrell/trello-macos/releases/latest

github:
  user: nathanbirrell
  repo: trello-macos
